steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.production.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=qoodish
      - --key=qoodish
  - name: node:13.3.0-alpine
    entrypoint: sh
    args:
      - -c
      - |
        yarn
        yarn build:prod
    env:
      - 'PICKED_UP_MAP_ID=${_PICKED_UP_MAP_ID}'
      - 'API_ENDPOINT=${_API_ENDPOINT}'
      - 'ENDPOINT=${_ENDPOINT}'
  - name: gcr.io/kaniko-project/executor
    args:
      - --cache=true
      - --cache-ttl=6h
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME:latest
