steps:
  - id: secret-manager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        gcloud beta secrets versions access latest --secret=DOTENV_WEB > .env
  - name: node:13.7.0-alpine
    entrypoint: sh
    args:
      - -c
      - |
        yarn
        yarn build:prod
    env:
      - PICKED_UP_MAP_ID=${_PICKED_UP_MAP_ID}
      - API_ENDPOINT=${_API_ENDPOINT}
      - ENDPOINT=${_ENDPOINT}
  - name: gcr.io/kaniko-project/executor
    args:
      - --cache=true
      - --cache-ttl=6h
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME:latest
